version: 0.2

  build:
    commands:
      - echo Build started on `date`
      - cd $CODEBUILD_SRC_DIR/aws_tester
      - docker run --rm -v "$PWD":/usr/src/myapp -w /usr/src/myapp public.ecr.aws/docker/library/golang:1.18 go test ./... > result
artifacts:
  files:
    - result
