version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - echo AWS_DEFAULT_REGION - $AWS_DEFAULT_REGION
      - echo AWS_ACCOUNT_ID - $AWS_ACCOUNT_ID
      - echo AWS_DEFAULT_REGION - $AWS_DEFAULT_REGION
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username tedychange --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

  build:
    commands:
      - docker run --rm -v "$PWD":/usr/src/myapp -w /usr/src/myapp public.ecr.aws/docker/library/golang:1.18 go test ./... > result
artifacts:
  files:
    - result
