version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.13
  build:
    commands:
      - echo Building the Go code...
      - cd $CODEBUILD_SRC_DIR/aws_tester
      - go test ./... > result
artifacts:
  files:
    - result
